Web/Front/Controllers/DepositController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DFramework;
using Dotpay.Command;
using Dotpay.Common;
using Dotpay.Common.Enum;
using Dotpay.Front.Validators;
using Dotpay.Front.ViewModel;
using Dotpay.FrontQueryService;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Dotpay.Front.YiSheng;

namespace Dotpay.Front.Controllers
{
    public class DepositController : BaseController
    {
        [Route("~/deposit")]
        [Route("~/deposit/index")]
        public ActionResult Index()
        {
            return View();
        }
        [Route("~/deposit/alipay")]
        public ActionResult Alipay()
        {
            return View();
        }
        [Route("~/deposit/taobao")]
        public ActionResult Taobao()
        {
            return View();
        }


        #region 易生支付充值接口

        #region 易生充值跳转
        [HttpGet]
        [Route("~/deposit/epredirect")]
        public ActionResult YiShengRedirect(int? errorCode, string bank, string orderBizNo, decimal amount)
        {
            if (errorCode.HasValue || string.IsNullOrEmpty(bank) || string.IsNullOrEmpty(orderBizNo) || amount <= 0)
            {
                ViewBag.ErrorMessage = DotpayJsonResult.SystemError.Message;
            }
            else
            {
                var con = new EasypayConfig();
                var partner = con.Partner;
                var key = con.Key;
                var sellerEmail = con.SellerEmail;
                var inputCharset = con.InputCharset;
                var notifyUrl = con.NotifyUrl;
                var returnUrl = con.ReturnUrl;
                var signType = con.SignType;
                //必填参数
                var outTradeNo = orderBizNo;                                  //请与贵网站订单系统中的唯一订单号匹配
                var subject = "点付充值";                                     //订单名称，显示在易生支付收银台里的“商品名称”里。
                var body = "Dotpayco";                                        //订单描述、订单详细、订单备注，显示在易生支付收银台里的“商品描述”里
                var totalFee = amount.ToString("0.##");                       //订单总金额，显示在易生支付收银台里的“应付总额”里


                var paymethod = "bankDirect";                                 //默认支付方式，三个值可选：bankPay(网银); directPay(账户余额); bankDirect(银行直联) 
                var buyerEmail = "";
                //构造请求函数，无需修改
                var easyService = new EasypayService(partner, sellerEmail, returnUrl, notifyUrl, outTradeNo, subject, body,
                                                     totalFee, paymethod, bank, buyerEmail, key, inputCharset, signType);
                ViewBag.FromHtml = easyService.BuildForm();
            }
            return View();
        }
        #endregion

        #region 易生Callback
        #region easy pay return
        [HttpGet]
        [Route("~/deposit/epreturn")]
        public async Task<ActionResult> EasypayReturn()
        {
            var @params = new SortedDictionary<string, string>();

            ViewBag.Result = DotpayJsonResult.CreateFailResult(this.Lang("easypayInvlidResult"));
            foreach (KeyValuePair<string, object> item in Request.Form)
            {
                @params.Add(item.Key, item.Value.ToString());
            }
            foreach (KeyValuePair<string, object> item in Request.QueryString)
            {
                @params.Add(item.Key, item.Value.ToString());
            }

            EasypayConfig con = new EasypayConfig();
            string partner = con.Partner;
            string key = con.Key;
            string input_charset = con.InputCharset;
            string sign_type = con.SignType;
            string transport = con.Transport;

            if (@params.Count > 0)
            {
                EasypayNotify easyNotify = new EasypayNotify(@params, @params["notify_id"], partner, key, input_charset, sign_type, transport);
                string responseTxt = easyNotify.ResponseTxt; //获取远程服务器ATN结果，验证是否是易生支付服务器发来的请求
                string sign = @params["notify_id"];          //获取易生支付反馈回来的sign结果
                string mysign = easyNotify.Mysign;           //获取通知返回后计算后（验证）的签名结果

                //写日志记录（若要调试，请取消下面两行注释）
                string sWord = "easy pay return:responseTxt=" + responseTxt + "\n return_url_log:sign=" + Request.Params["sign"] + "&mysign=" + mysign + "\n return回来的参数：" + easyNotify.PreSignStr;
                Log.Debug(sWord);

                //判断responsetTxt是否为true，生成的签名结果mysign与获得的签名结果sign是否一致
                //responsetTxt的结果不是true，与服务器设置问题、合作身份者ID、notify_id一分钟失效有关
                //mysign与sign不等，与安全校验码、请求时的参数格式（如：带自定义参数等）、编码格式有关
                //判断responsetTxt是否为ture，生成的签名结果mysign与获得的签名结果sign是否一致
                //responsetTxt的结果不是true，与服务器设置问题、合作身份者ID、notify_id一分钟失效有关
                //mysign与sign不等，与安全校验码、请求时的参数格式（如：带自定义参数等）、编码格式有关

                if (responseTxt == "true" && sign == mysign)//验证成功
                {
                    /////////////////////////////////////////////////////////////////////////////////////////////////////////////
                    //请在这里加上商户的业务逻辑程序代码

                    //——请根据您的业务逻辑来编写程序（以下代码仅作参考）——
                    //获取易生支付的通知返回参数，可参考技术文档中页面跳转同步通知参数列表
                    var tradeNo = Request.Params["trade_no"];      //易生支付交易号
                    var orderNo = Request.Params["out_trade_no"];	//获取订单号
                    var totalAmount = Convert.ToDecimal(Request.Params["total_fee"]);	//获取总金额
                    //var subject = Request.Params["subject"];        //商品名称、订单名称
                    //var body = Request.Params["body"];              //商品描述、订单备注、描述
                    //var buyer_email = Request.Params["buyer_email"];//买家易生支付买家账号
                    var trade_status = Request.Params["trade_status"];//交易状态

                    //如果交易完成
                    if (trade_status == "TRADE_FINISHED")
                    {
                        //查询我们的订单号对应的充值记录，得到txid后执行cmd 
                        var txQuery = IoC.Resolve<ITransactionQuery>();
                        Guid txid = await txQuery.GetDepositTransactionIdBySeqNo(orderNo);
                        try
                        {
                            var cmd = new ConfirmDepositCommand(txid, tradeNo, totalAmount);
                            await this.CommandBus.SendAsync(cmd);

                            if (cmd.CommandResult == ErrorCode.None)
                            {
                                ViewBag.Result = DotpayJsonResult.CreateSuccessResult(this.Lang("depositSuccessNotice", totalAmount.ToString("0.##")));
                            }
                            else if (cmd.CommandResult == ErrorCode.DepositAmountNotMatch)
                            {
                                Log.Debug("easy pay订单金额不匹配失败了" + orderNo + trade_status);
                                ViewBag.Result = DotpayJsonResult.CreateFailResult("order amount not match.");
                                //充值的金额不匹配
                                //ViewBag.Success = false;
                            }
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Result = DotpayJsonResult.SystemError;
                            Log.Debug("订单失败了" + orderNo + trade_status);
                        }
                    }
                    else
                    {
                        ViewBag.Result = DotpayJsonResult.SystemError;
                        //处理支付失败的订单
                        Log.Debug("订单失败了" + orderNo + trade_status);
                    }
                }
                else
                {
                    Log.Debug("易生支付返回结果验证失败");
                }
            }
            else
            {
                Log.Debug("易生支付返回参数无效");
            }
            return View("DepositResult");
        }
        #endregion

        #region easy pay notice
        [HttpGet]
        [Route("~/deposit/epnotice")]
        public async Task<ActionResult> EasypayNotice()
        {
            var @params = new SortedDictionary<string, string>();
            foreach (KeyValuePair<string, object> item in Request.Form)
            {
                @params.Add(item.Key, item.Value.ToString());
            }
            foreach (KeyValuePair<string, object> item in Request.QueryString)
            {
                @params.Add(item.Key, item.Value.ToString());
            }

            EasypayConfig con = new EasypayConfig();
            string partner = con.Partner;
            string key = con.Key;
            string input_charset = con.InputCharset;
            string sign_type = con.SignType;
            string transport = con.Transport;

            if (@params.Count > 0)
            {
                EasypayNotify easyNotify = new EasypayNotify(@params, @params["notify_id"], partner, key, input_charset, sign_type, transport);
                string responseTxt = easyNotify.ResponseTxt; //获取远程服务器ATN结果，验证是否是易生支付服务器发来的请求
                string sign = @params["notify_id"];          //获取易生支付反馈回来的sign结果
                string mysign = easyNotify.Mysign;           //获取通知返回后计算后（验证）的签名结果

                //写日志记录（若要调试，请取消下面两行注释）
                string sWord = "easy pay notice:responseTxt=" + responseTxt + "\n return_url_log:sign=" + Request.Params["sign"] + "&mysign=" + mysign + "\n return回来的参数：" + easyNotify.PreSignStr;
                Log.Debug(sWord);

                //判断responsetTxt是否为true，生成的签名结果mysign与获得的签名结果sign是否一致
                //responsetTxt的结果不是true，与服务器设置问题、合作身份者ID、notify_id一分钟失效有关
                //mysign与sign不等，与安全校验码、请求时的参数格式（如：带自定义参数等）、编码格式有关
                //判断responsetTxt是否为ture，生成的签名结果mysign与获得的签名结果sign是否一致
                //responsetTxt的结果不是true，与服务器设置问题、合作身份者ID、notify_id一分钟失效有关
                //mysign与sign不等，与安全校验码、请求时的参数格式（如：带自定义参数等）、编码格式有关

                if (responseTxt == "true" && sign == mysign)//验证成功
                {

Web/Front/Controllers/ProfileController.cs
using System;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DFramework;
using Dotpay.Command;
using Dotpay.Common;
using Dotpay.Front.Validators;
using Dotpay.Front.ViewModel;
using Dotpay.FrontQueryService;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Dotpay.Front.Controllers
{
    public class ProfileController : BaseController
    {
        [Route("~/i")]
        public async Task<ActionResult> Index()
        {
            var accountQuery = IoC.Resolve<IAccountQuery>();
            var txQuery = IoC.Resolve<ITransactionQuery>();
            var currentUser = this.CurrentUser;
            var userBalances = await accountQuery.GetAccountBalanceByOwnerId(currentUser.UserId);
            ViewBag.Balances = userBalances;
            var indexTxs = await txQuery.GetLastTenTransationByAccountId(currentUser.AccountId);
            var dateStart = DateTime.Now.AddDays(-30);
            var end = DateTime.Now;
            var depositSum = await txQuery.SumDepositAmount(currentUser.AccountId, dateStart, end);
            var transferTuple = await txQuery.SumTransferOutAndInAmount(currentUser.AccountId, dateStart, end);



            ViewBag.RecentTxs = indexTxs;
            ViewBag.Out = transferTuple.Item1;
            ViewBag.In = depositSum + transferTuple.Item2;
            return View();
        }

        public ActionResult ProfileHeader(int activeIndex)
        {
            ViewBag.ActiveIndex = activeIndex;
            return View();
        }

        [Route("~/profile")]
        [Route("~/profile/index")]
        public async Task<ActionResult> ProfileIndex()
        {
            var accountQuery = IoC.Resolve<IAccountQuery>();
            var userBalances = await accountQuery.GetAccountBalanceByOwnerId(this.CurrentUser.UserId);
            ViewBag.Balances = userBalances;
            return View();
        }

        #region 设置支付密码
        [Route("~/profile/setpaymentpassword")]
        [HttpGet]
        public ActionResult SetPaymentPassword(string source)
        {
            ViewBag.Message = this.Lang("transferPaymentPasswordNotInit");
            return View();
        }

        #endregion

        #region 实名认证
        [HttpGet]
        [Route("~/profile/identityverify")]
        public ActionResult IdentityVerify(string source)
        {
            if (source.NullSafe().Trim().Equals("transfer"))
                ViewBag.Message = this.Lang("verifyIdentityFirst");
            return View();
        }

        [HttpPost]
        [Route("~/profile/identityverify")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> IdentityVerify(IdentityInfoViewModel identity)
        {
            var validator = new IdentityInfoViewModelValidator();
            var validResult = validator.Validate(identity);
            var result = DotpayJsonResult.SystemError;
            if (validResult.IsValid)
            {
                var cmd = new UserIdentityVerifyCommand(this.CurrentUser.UserId, identity.FullName, identity.IdNo, identity.IdType);

                await this.CommandBus.SendAsync(cmd);
                this.CurrentUser.IdentityInfo = identity;
                result = DotpayJsonResult.Success;
            }

            return Json(result);
        }

        #endregion
    }
}

Web/Front/Views/Deposit/Alipay.cshtml
@using Dotpay.Common
@using Dotpay.Common.Enum
@using Dotpay.Front.Controllers
@using Dotpay.Language
@{
    Layout = "~/Views/Shared/_Layout_Profile.cshtml";
}
@Html.Action("ProfileHeader", "Profile", new { activeIndex = 3 })
<div class="profile-main">
    <div class="sub-nav ">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/deposit/index">在线支付<i class="icon-chevron-right"></i></a>
                </li>
                <li class="active">
                    <a href="#">支付宝<i class="icon-chevron-right"></i></a>
                </li>
                <li>
                    <a href="/deposit/taobao">淘宝<i class="icon-chevron-right"></i></a>
                </li>
            </ul>
        </div>
    </div> 
    <div class="container deposit">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <div>
                <h4>支付宝充值</h4>
            </div>
            <hr/>
            <div class="note" id="noticeBox" style="display: none;">
            </div>
            <form id="depositAlipayForm" class="form-horizontal" method="POST" action="~/deposit/alipay/submit">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label class="col-sm-2 col-md-2 control-label" for="amount">充值金额</label>
                    <div class="col-sm-4 controls">
                        <input class="form-control" id="amount" name="amount" type="text" autocomplete="off">
                    </div>
                    <div class="col-sm-2 col-md-2   controls">
                        <input type="submit" class="btn btn-primary btn-large btn-block" value="下一步">
                    </div>
                </div>
            </form>
        </div>
        <script>
        $(document).ready(function () {
            $.getScript('/assets/js/deposit.js').done(function () {
                Deposit.initAlipayDeposit();
            });
        });
        </script>
    </div>
</div>

Web/Front/Views/Deposit/AlipayRedirect.cshtml
@using Dotpay.Common
@using Dotpay.Common.Enum
@using Dotpay.Front.Controllers
@using Dotpay.Language
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>点付</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="点付 , 您的快捷支付专家" name="description" />
    <script src="~/assets/plugins/jquery/jquery-1.11.2.min.js"></script>
</head>
<body>
    @if (ViewBag.Result == true)
    {
        @("redirct...please wait")
        <form id="payform" style="display: none" action="https://shenghuo.alipay.com/send/payment/fill.htm" method="POST">
            <label>account</label> <input type="text" name="optEmail" value="@ViewBag.Account" />
            <label>amount</label> <input type="text" name="payAmount" value="@ViewBag.Amount" />
            <label>memo</label> <input type="text" name="title" value="@ViewBag.Seq" />
            <input type="hidden" name="memo" value="@ViewBag.Seq" />
        </form>
    }
    else
    {
        @("Invalid link.")
    }
    <script>
        $("#payform").submit();
    </script>
</body>
</html>

Web/Front/Views/Deposit/DepositResult.cshtml
@using Dotpay.Language

@{
    Layout = null;
}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>点付</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="点付 , 您的快捷支付专家" name="description" />
    <!--  BEGIN BASE CSS STYLE  -->
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/css/animate.min.css" rel="stylesheet" />
    <link href="/assets/css/style@(ViewBag.Debug==true?"":".min").css" rel="stylesheet" />
    <link href="/assets/css/style-responsive@(ViewBag.Debug==true?"":".min").css" rel="stylesheet" />
    <link href="/assets/plugins/formvalidation/css/formValidation.min.css" rel="stylesheet" />
    <link href="/assets/css/theme/default@(ViewBag.Debug==true?"":".min").css" rel="stylesheet" />
    <link href="/assets/css/lang/@(ViewBag.Lang != "zh-cn" && ViewBag.Lang != "zh-tw"?"other":ViewBag.Lang).css" id="fontstyle" rel="stylesheet" />
    <!-- END BASE CSS STYLE -->
    <!-- end #page-container -->

</head>
<body>
    <!-- begin #header -->
    <div id="header" class="header navbar navbar-default navbar-profile" data-state-change="disabled">
        <!-- begin container -->
        <div class="container">
            <!-- begin navbar-header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">
                    <span class="brand-logo"></span>
                    <span class="brand-text">
                        <span class="text-theme">@Html.Lang("DotpayLogoTitle")</span>|收银台
                    </span>
                </a>
            </div>
            <!-- end navbar-header -->
        </div>
        <!-- end container -->
    </div>
    <!-- end #header -->
    <div class="container">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">
                    @Html.Lang("depositResult")
                </div>
                <div class="panel-body form-horizontal">
                    <div class="alert@(ViewBag.Result.Code == 1 ? " alert-success" : " alert-danger") fade in"> 
                        <i class="fa fa-check fa-2x pull-left"></i>
                        <p>@ViewBag.Result.Message</p>
                    </div>
                    <a href="/deposit">@Html.Lang("continueDeposit")</a>
                    <a href="/deposit/list">@Html.Lang("viewDepositRecord")</a>
                    <a href="/i">@Html.Lang("returnToI")</a>
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("_ProfileFooter")
</body>
</html>

Web/Front/Views/Deposit/Index.cshtml
@using Dotpay.Common
@using Dotpay.Common.Enum
@using Dotpay.Front.Controllers
@using Dotpay.Language
@{
    Layout = "~/Views/Shared/_Layout_Profile.cshtml";
}
@Html.Action("ProfileHeader", "Profile", new { activeIndex = 3 })
<div class="profile-main">
    <div class="sub-nav ">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="#">在线支付<i class="icon-chevron-right"></i></a>
                </li>
                <li>
                    <a href="/deposit/alipay">支付宝<i class="icon-chevron-right"></i></a>
                </li>
                <li>
                    <a href="/deposit/taobao">淘宝<i class="icon-chevron-right"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container deposit">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <div>
                <h4>在线支付</h4>
            </div>
            <hr />
            <form id="depositForm" class="form-horizontal" method="POST" action="~/deposit/epsubmit">
                <div class="row selectbank">
                    @Html.AntiForgeryToken()
                    <ul>
                        <li>
                            <input name="bank" type="radio" value="ICBC" checked="checked" />
                            <label><img src="~/assets/img/bank/ICBC_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="ABC" />
                            <label><img src="~/assets/img/bank/ABC_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="CCB" />
                            <label><img src="~/assets/img/bank/CCB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="CMB" />
                            <label><img src="~/assets/img/bank/CMB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="BOC" />
                            <label><img src="~/assets/img/bank/BOC_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="HSBC" />
                            <label><img src="~/assets/img/bank/COMM_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="CEB" />
                            <label><img src="~/assets/img/bank/CEB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="CITIC" />
                            <label><img src="~/assets/img/bank/CITIC_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="SPDB" />
                            <label><img src="~/assets/img/bank/SPDB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="SDB" />
                            <label><img src="~/assets/img/bank/SDB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="CMBC" />
                            <label><img src="~/assets/img/bank/CMBC_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="HXB" />
                            <label><img src="~/assets/img/bank/HXB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="PSBC" />
                            <label><img src="~/assets/img/bank/PSBC_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="HSBK" />
                            <label><img src="~/assets/img/bank/HSBK_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="HZBANK" />
                            <label><img src="~/assets/img/bank/HZBANK_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="NJB" />
                            <label><img src="~/assets/img/bank/NJB_OUT.png" /></label>
                        </li>
                        <li>
                            <input name="bank" type="radio" value="SHBANK" />
                            <label><img src="~/assets/img/bank/SHBANK_OUT.png" /></label>
                        </li>
                    </ul>
                </div>
                <hr />
                <div class="form-group">
                    <label class="col-sm-2 col-md-2 control-label" for="amount">充值金额</label>
                    <div class="col-sm-4 controls">
                        <input class="form-control" id="amount" name="amount" type="text" autocomplete="off">
                    </div>
                    <div class="col-sm-2 col-md-2   controls">
                        <input type="submit" class="btn btn-primary btn-large btn-block" value="确定">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $.getScript('/assets/js/deposit.js').done(function () {
                Deposit.initOnlineDeposit();
            });
        });
    </script>
</div>

Web/Front/Views/Deposit/Taobao.cshtml
@using Dotpay.Common
@using Dotpay.Common.Enum
@using Dotpay.Front.Controllers
@using Dotpay.Language
@{
    Layout = "~/Views/Shared/_Layout_Profile.cshtml";
}
@Html.Action("ProfileHeader", "Profile", new { activeIndex = 3 })
<div class="profile-main">
    <div class="sub-nav ">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/deposit/index">在线支付<i class="icon-chevron-right"></i></a>
                </li>
                <li>
                    <a href="/deposit/alipay">支付宝<i class="icon-chevron-right"></i></a>
                </li>
                <li class="active">
                    <a href="#">淘宝<i class="icon-chevron-right"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container deposit">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <div>
                <h4>淘宝自动充值</h4>
            </div>
            <hr />
            <div>
                <h5>充值说明：</h5>
                <p style="margin: 10px;">Dotpayco提供自动充值服务，请在充值前仔细阅读商品说明。</p>
                <p style="margin: 10px;">如在充值遇到问题，请点击充值进度查询，查看原因。</p>
                <p style="margin: 10px;">更多问题咨询，请加入QQ群385108034咨询管理员或致电021-31608155</p>
                <a href="http://shop113155095.taobao.com/category-1067094686.htm" class="btn btn-success btn-large">进入淘宝充值</a>
                <a href="/deposit/records" class="btn btn-info btn-large">查看充值记录</a>
            </div>
        </div>
    </div> 
</div>

Web/Front/Views/Deposit/YiShengRedirect.cshtml
@using Dotpay.Common
@using Dotpay.Common.Enum
@using Dotpay.Front.Controllers
@using Dotpay.Language
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>点付</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="点付 , 您的快捷支付专家" name="description" />
</head>
<body>
    @{
        var a = MvcHtmlString.Create(ViewBag.FromHtml);
    }
    @a
</body>
</html>